/**
 * Types for getting the initial data from Restaurants
 */
export const GET_RESTAURANTS_INITIAL_DATA = 'GET_RESTAURANTS_INITIAL_DATA';
export const GET_RESTAURANTS_INITIAL_DATA_SUCCESS = 'GET_RESTAURANTS_INITIAL_DATA_SUCCESS';
export const GET_RESTAURANTS_INITIAL_DATA_ERROR = 'GET_RESTAURANTS_INITIAL_DATA_ERROR';

/**
 * Types for Login
 */
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

/**
 * Types for Logout
 */
export const POST_LOGOUT = 'POST_LOGOUT';

/**
 * Types for getting the restaurant Detail
 */
export const GET_RESTAURANT_DETAIL_INITIAL_DATA = 'GET_RESTAURANT_DETAIL_INITIAL_DATA';
export const GET_RESTAURANT_DETAIL_INITIAL_DATA_SUCCESS = 'GET_RESTAURANT_DETAIL_INITIAL_DATA_SUCCESS';
export const GET_RESTAURANT_DETAIL_INITIAL_DATA_ERROR = 'GET_RESTAURANT_DETAIL_INITIAL_DATA_ERROR';

/**
 * Types for getting the dish Detail
 */
export const GET_DISH_DETAIL_INITIAL_DATA = 'GET_DISH_DETAIL_INITIAL_DATA';
export const GET_DISH_DETAIL_INITIAL_DATA_SUCCESS = 'GET_DISH_DETAIL_INITIAL_DATA_SUCCESS';
export const GET_DISH_DETAIL_INITIAL_DATA_ERROR = 'GET_DISH_DETAIL_INITIAL_DATA_ERROR';


/**
 * Types for getting the menu Detail
 */
export const GET_MENU_DETAIL_INITIAL_DATA = 'GET_MENU_DETAIL_INITIAL_DATA';
export const GET_MENU_DETAIL_INITIAL_DATA_SUCCESS = 'GET_MENU_DETAIL_INITIAL_DATA_SUCCESS';
export const GET_MENU_DETAIL_INITIAL_DATA_ERROR = 'GET_MENU_DETAIL_INITIAL_DATA_ERROR';

export const APP_START = 'APP_START';