/**
 * Types for getting the initial data from Restaurants
 */
export const GET_RESTAURANTS_INITIAL_DATA = 'GET_RESTAURANTS_INITIAL_DATA';
export const GET_RESTAURANTS_INITIAL_DATA_SUCCESS = 'GET_RESTAURANTS_INITIAL_DATA_SUCCESS';
export const GET_RESTAURANTS_INITIAL_DATA_ERROR = 'GET_RESTAURANTS_INITIAL_DATA_ERROR';

/**
 * Types for Login
 */
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const RESET_PASSWORD_CONFIRM = 'RESET_PASSWORD_CONFIRM';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_ERROR = 'RESET_PASSWORD_CONFIRM_ERROR';

/**
 * Types for authhenticated
 */
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_ERROR = 'AUTHENTICATED_ERROR';

/**
 * Types for Logout
 */
export const POST_LOGOUT = 'POST_LOGOUT';

/**
 * Types for getting the restaurant Detail
 */
export const GET_RESTAURANT_DETAIL_INITIAL_DATA = 'GET_RESTAURANT_DETAIL_INITIAL_DATA';
export const GET_RESTAURANT_DETAIL_INITIAL_DATA_SUCCESS = 'GET_RESTAURANT_DETAIL_INITIAL_DATA_SUCCESS';
export const GET_RESTAURANT_DETAIL_INITIAL_DATA_ERROR = 'GET_RESTAURANT_DETAIL_INITIAL_DATA_ERROR';

/**
 * Types for getting the restaurant tree view Detail
 */
export const GET_RESTAURANT_TREE_VIEW_DETAIL_DATA = 'GET_RESTAURANT_TREE_VIEW_DETAIL_DATA';
export const GET_RESTAURANT_TREE_VIEW_DETAIL_DATA_SUCCESS = 'GET_RESTAURANT_TREE_VIEW_DETAIL_DATA_SUCCESS';
export const GET_RESTAURANT_TREE_VIEW_DETAIL_DATA_ERROR = 'GET_RESTAURANT_TREE_VIEW_DETAIL_DATA_ERROR';

/**
 * Types for getting the dish Detail
 */
export const GET_DISH_DETAIL_INITIAL_DATA = 'GET_DISH_DETAIL_INITIAL_DATA';
export const GET_DISH_DETAIL_INITIAL_DATA_SUCCESS = 'GET_DISH_DETAIL_INITIAL_DATA_SUCCESS';
export const GET_DISH_DETAIL_INITIAL_DATA_ERROR = 'GET_DISH_DETAIL_INITIAL_DATA_ERROR';


/**
 * Types for getting the menu Detail
 */
export const GET_MENU_DETAIL_INITIAL_DATA = 'GET_MENU_DETAIL_INITIAL_DATA';
export const GET_MENU_DETAIL_INITIAL_DATA_SUCCESS = 'GET_MENU_DETAIL_INITIAL_DATA_SUCCESS';
export const GET_MENU_DETAIL_INITIAL_DATA_ERROR = 'GET_MENU_DETAIL_INITIAL_DATA_ERROR';

export const APP_START = 'APP_START';

export const ADD_CATEGORY_DATA = 'ADD_CATEGORY_DATA';
export const ADD_CATEGORY_DATA_SUCCESS = 'ADD_CATEGORY_DATA_SUCCESS';
export const ADD_CATEGORY_DATA_ERROR = 'ADD_CATEGORY_DATA_ERROR';

export const EDIT_CATEGORY_DATA = 'EDIT_CATEGORY_DATA';
export const EDIT_CATEGORY_DATA_SUCCESS = 'EDIT_CATEGORY_DATA_SUCCESS';
export const EDIT_CATEGORY_DATA_ERROR = 'EDIT_CATEGORY_DATA_ERROR';

export const DELETE_CATEGORY_DATA = 'DELETE_CATEGORY_DATA';
export const DELETE_CATEGORY_DATA_SUCCESS = 'DELETE_CATEGORY_DATA_SUCCESS';
export const DELETE_CATEGORY_DATA_ERROR = 'DELETE_CATEGORY_DATA_ERROR';

export const ADD_ITEM_DATA = 'ADD_ITEM_DATA';
export const ADD_ITEM_DATA_SUCCESS = 'ADD_ITEM_DATA_SUCCESS';
export const ADD_ITEM_DATA_ERROR = 'ADD_ITEM_DATA_ERROR';

export const EDIT_ITEM_DATA = 'EDIT_ITEM_DATA';
export const EDIT_ITEM_DATA_SUCCESS = 'EDIT_ITEM_DATA_SUCCESS';
export const EDIT_ITEM_DATA_ERROR = 'EDIT_ITEM_DATA_ERROR';

export const DELETE_ITEM_DATA = 'DELETE_ITEM_DATA';
export const DELETE_ITEM_DATA_SUCCESS = 'DELETE_ITEM_DATA_SUCCESS';
export const DELETE_ITEM_DATA_ERROR = 'DELETE_ITEM_DATA_ERROR';

export const ADD_RESTAURANT_DATA = 'ADD_RESTAURANT_DATA';
export const ADD_RESTAURANT_DATA_SUCCESS = 'ADD_RESTAURANT_DATA_SUCCESS';
export const ADD_RESTAURANT_DATA_OWNER_SUCCESS = 'ADD_RESTAURANT_DATA_OWNER_SUCCESS';
export const ADD_RESTAURANT_DATA_ERROR = 'ADD_RESTAURANT_DATA_ERROR';

export const EDIT_RESTAURANT_DATA = 'EDIT_RESTAURANT_DATA';
export const EDIT_RESTAURANT_DATA_SUCCESS = 'EDIT_RESTAURANT_DATA_SUCCESS';
export const EDIT_RESTAURANT_DATA_ERROR = 'EDIT_RESTAURANT_DATA_ERROR';

export const DELETE_RESTAURANT_DATA = 'DELETE_RESTAURANT_DATA';
export const DELETE_RESTAURANT_DATA_SUCCESS = 'DELETE_RESTAURANT_DATA_SUCCESS';
export const DELETE_RESTAURANT_DATA_ERROR = 'DELETE_RESTAURANT_DATA_ERROR';

export const ADD_MENU_DATA = 'ADD_MENU_DATA';
export const ADD_MENU_DATA_SUCCESS = 'ADD_MENU_DATA_SUCCESS';
export const ADD_MENU_DATA_ERROR = 'ADD_MENU_DATA_ERROR';

export const EDIT_MENU_DATA = 'EDIT_MENU_DATA';
export const EDIT_MENU_DATA_SUCCESS = 'EDIT_MENU_DATA_SUCCESS';
export const EDIT_MENU_DATA_ERROR = 'EDIT_MENU_DATA_ERROR';

export const ADD_USER_DATA = 'ADD_USER_DATA';
export const ADD_USER_DATA_SUCCESS = 'ADD_USER_DATA_SUCCESS';
export const ADD_USER_DATA_ERROR = 'ADD_USER_DATA_ERROR';

export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const DELETE_USER_DATA_SUCCESS = 'DELETE_USER_DATA_SUCCESS';
export const DELETE_USER_DATA_ERROR = 'DELETE_USER_DATA_ERROR';

export const ALERT_ACTIVATE = 'ALERT_ACTIVATE'
export const ALERT_DEACTIVATE = 'ALERT_DEACTIVATE'

export const DELETE_MENU_DATA = 'DELETE_MENU_DATA';
export const DELETE_MENU_DATA_SUCCESS = 'DELETE_MENU_DATA_SUCCESS';
export const DELETE_MENU_DATA_ERROR = 'DELETE_MENU_DATA_ERROR';

export const EDIT_USER_DATA = 'EDIT_USER_DATA';
export const EDIT_USER_DATA_SUCCESS = 'EDIT_USER_DATA_SUCCESS';
export const EDIT_USER_DATA_ERROR = 'EDIT_USER_DATA_ERROR';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
